apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-example
  namespace: spark-job
spec:
  type: Python
  mode: cluster
  image: "otaciliopsf/spark-py:job-example"
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/app.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
    env:
      - name: AZURE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: job-example
            key: AZURE_CLIENT_ID
      - name: AZURE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: job-example
            key: AZURE_CLIENT_SECRET
      - name: AZURE_TENANT_ID
        valueFrom:
          secretKeyRef:
            name: job-example
            key: AZURE_TENANT_ID
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
